import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/fonts/page";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} max-w-2xl mx-auto items-center px-2 my-4`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
